// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

// ...



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQ7x2FAxIXmYsjLZBfvP2LzLVhjBpRGE',
    appId: '1:465635193904:web:3ebc1af7c96130fd7b29f5',
    messagingSenderId: '465635193904',
    projectId: 'projetopiloto-1c6ee5a7',
    authDomain: 'projetopiloto-1c6ee5a7.firebaseapp.com',
    storageBucket: 'projetopiloto-1c6ee5a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVzkhYzZMypdyc8ece4eZ3mK76oNbkD4',
    appId: '1:465635193904:android:91ac9c8161c00a507b29f5',
    messagingSenderId: '465635193904',
    projectId: 'projetopiloto-1c6ee5a7',
    storageBucket: 'projetopiloto-1c6ee5a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0_LROVHzMfj7iG1aKJCA43UegUT_LkFA',
    appId: '1:465635193904:ios:da7ea049b17cb32c7b29f5',
    messagingSenderId: '465635193904',
    projectId: 'projetopiloto-1c6ee5a7',
    storageBucket: 'projetopiloto-1c6ee5a7.firebasestorage.app',
    iosBundleId: 'com.example.agmpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0_LROVHzMfj7iG1aKJCA43UegUT_LkFA',
    appId: '1:465635193904:ios:da7ea049b17cb32c7b29f5',
    messagingSenderId: '465635193904',
    projectId: 'projetopiloto-1c6ee5a7',
    storageBucket: 'projetopiloto-1c6ee5a7.firebasestorage.app',
    iosBundleId: 'com.example.agmpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQ7x2FAxIXmYsjLZBfvP2LzLVhjBpRGE',
    appId: '1:465635193904:web:b8c369bfa77122317b29f5',
    messagingSenderId: '465635193904',
    projectId: 'projetopiloto-1c6ee5a7',
    authDomain: 'projetopiloto-1c6ee5a7.firebaseapp.com',
    storageBucket: 'projetopiloto-1c6ee5a7.firebasestorage.app',
  );
}
